services:
  db:
    image: postgres:16-alpine
    container_name: kindercare-db
    environment:
      POSTGRES_DB: kindercare
      POSTGRES_USER: kindercare
      POSTGRES_PASSWORD: kindercare
    ports:
      - "5433:5432"
    volumes:
      - kindercare-data:/var/lib/postgresql/data

volumes:
  kindercare-data:
