services:
  - type: web
    name: kindercare-backend
    runtime: docker
    region: frankfurt
    plan: free
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: production
    healthCheckPath: /api/children
