services:
  - type: web
    name: kindercare-backend-java
    runtime: java
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: production
    healthCheckPath: /api/children