//src/main/resources/application.properties
//Spring App mit GET-Route gepusht :
// ./gradlew bootRun  and then localhost:9090
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.github.node-gradle.node' version '7.0.2'
}

group = 'de.htw-berlin'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '21'
	targetCompatibility = '21'
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

node {
	download = true
	version = '20.19.0'
	workDir = file("${project.projectDir}/src/main/frontend/node_modules")
	nodeProjectDir = file("${project.projectDir}/src/main/frontend")
}

task buildFrontend(type: NpmTask) {
	dependsOn npmInstall
	args = ['run', 'build']
}

processResources {
	// dependsOn buildFrontend  // Commented out since frontend is built manually
	from("${project.projectDir}/src/main/frontend/dist") {
		into "static"
	}
	duplicatesStrategy = 'include'
}

tasks.named('test') {
	useJUnitPlatform()
}
